### ISSUE TITLE
Bonus 1 - Tracking Fish

### ISSUE THREAD

**Issue by GonzalesMatthew** [GonzalesMatthew/ASSIGNMENT-Bear-Watcher#5]
- [ ] As a user, I should be able to click something on each bear to indicate it has just tried to catch a fish.
- [ ] As a user, I should be able to click something on each bear to indicate it has just successfully caught a fish.
- [ ] As a user, looking at a bear card I should see time stamps and statuses for each time a bear caught a fish or attempted to catch a fish
- [x] As a user, looking at a bear card, I should see a total number of fish caught tally.

Tech Requirements:
- [x] enhance River array with necessary properties (attempt count, fish count, fishingLog)
- [ ] functions to track Attempt and Caught buttons
- [ ] above functions should push to bear's complex data (fishingLog) array
- [ ] cards should read fishingLog array
